include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    invalid_annotation_target: ignore
    public_member_api_docs: false

linter:
    rules:
      - always_use_package_imports
      - annotate_overrides
      - avoid_escaping_inner_quotes
      - avoid_final_parameters
      - avoid_positional_boolean_parameters
      - avoid_relative_lib_imports
      - avoid_single_cascade_in_expression_statements
      - avoid_unused_constructor_parameters
      - camel_case_extensions
      - prefer_const_declarations
      - camel_case_types
      - cascade_invocations
      - prefer_const_constructors_in_immutables
      - prefer_const_literals_to_create_immutables
      - prefer_const_constructors
      - prefer_constructors_over_static_methods
      - constant_identifier_names
      - directives_ordering
      - file_names
      - prefer_final_in_for_each
      - flutter_style_todos
      - prefer_contains
      - prefer_adjacent_string_concatenation
      - package_names
      - prefer_foreach
      - sort_constructors_first
      - prefer_interpolation_to_compose_strings
      - sort_unnamed_constructors_first
      - hash_and_equals
      - sort_child_properties_last
      - use_full_hex_values_for_flutter_colors
      - unawaited_futures
      - use_named_constants
      - use_colored_box
      - use_enums
      - prefer_for_elements_to_map_fromIterable
      - prefer_single_quotes
      - omit_local_variable_types
      - join_return_with_assignment
      - prefer_final_fields
      - no_duplicate_case_values